version: '2'
services:
    apache:
        build:
            context: ./
            dockerfile: build/apache.dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        depends_on:
            - admin
            - client
    client:
        build:
            context: ./
            dockerfile: build/client.dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - database
    admin:
        build:
            context: ./
            dockerfile: build/admin.dockerfile
        volumes:
            - ./:/var/www/
        depends_on:
            - database
    database:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wordpress
        ports:
            - "3306:3306"
