version: '2'
services:
    client:
        build:
            context: ./
            dockerfile: build/client.dockerfile
        volumes:
            - ./Laravel:/var/www/html/Laravel
        ports:
            - "8000:80"
        depends_on:
            - database
    database:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wordpress
        ports:
            - "3306:3306"
