version: '2'
services:
    nginx:
        build:
            context: ./
            dockerfile: build/nginx.dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - client
    client:
        build:
            context: ./
            dockerfile: build/client.dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - database
    admin:
        build:
            context: ./
            dockerfile: build/admin.dockerfile
        environment:
            - admin_password=*3DFb8DJo7iF3xc7TD
        volumes:
            - ./:/var/www/
        depends_on:
            - database
    database:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wordpress
        ports:
            - "3306:3306"
